#!/usr/bin/env bash
# Description: Make a script that launches golang program
# Date: 21/04/25
# Author: omitida

function help() {
    echo "
    ./makego [options] <filename>

    options
    =======
    -b  build and run a go file. This generate an executable file.
    -d  delete a go file.
    -g  generate and run a generic go file.
    -h  print the help function of the script.
    -t  to run a test file in the current working directory
    -n  to create all the files needed including the test file.
    -r  to run a specified go file
    "
}

# write out a basic go file
function generate_go_file() {
    filename="${1}"

    if [[ -e "${filename}" ]]; then
        echo "The file ${filename} exists, and can't be overwritten."
        exit 1
    fi

    # basic golang line to write to file
    echo "
        package main

        import (
            \"fmt\"
        )

        func main() {
            fmt.Println(\"Start Here...\")
        }
        " > "${filename}"
}

# check if the file has an extension check
# if it doesn't add one: Which should be go
function file_extension_check() {
    filename=${1}
    expected_extension="${2}"
    ext="${filename##*.}"
    if [[ "${ext}" != "${expected_extension}" ]]; then
        filename="${filename}.go"
    fi
}

function format_code() {
    filename=${1}
    gofmt "${filename}" > "${filename}_tmp"
    cat "${filename}_tmp" > "${filename}"
    rm "${filename}_tmp"
}

# check and start the script here
if [[ "${#}" -ne 2 ]]; then
    help
    exit 1
fi

# options string to use
optstring="b:d:g:r:n:t:h"

while getopts "${optstring}" opt; do
    case "${opt}" in
        b)
            filename="${OPTARG}"

            # call the function with parameters
            file_extension_check "${filename,,}" "go"
            generate_go_file "${filename}"
            format_code "${filename}"

            go mod init $(basename "${PWD}")
            go mod tidy

            go build .
            go run .
        ;;
        d)
            filename="${OPTARG}"
            filename=$(ls | grep -i "${filename}")

            if ! [[ -e "${filename}" ]]; then
                echo "${OPTARG} doesn't exists."
                exit 0
            fi

            while read -p "Do you want to delete the ${filename}? [yn]: " -r ans; do
                case "${ans,,}" in
                    y)
                        rm -rf "${filename}"
                        echo "${filename} deleted."
                        exit 0
                        ;;
                    n)
                        echo "${filename} NOT deleted."
                        exit 0
                        ;;
                    *)
                    echo "Use either y or n."
                    continue
                    ;;
                esac
            done
        ;;
        g)
            filename="${OPTARG}"

            # call the function with parameters
            file_extension_check "${filename,,}" "go"
            generate_go_file "${filename}"
            format_code "${filename}"

            directory="${filename%.*}"
            mkdir "${directory}" && mv "${filename}" "${directory}/main.go"
            cd "${directory}"
            go mod init "${directory}"
            go build .
            go run .
        ;;
        r)
             filename="${OPTARG}"
             file_extension_check "${filename,,}" "go"
             go run "${filename}"
        ;;
        n)
            filename="${OPTARG}"
            echo "Filename ${filename} is ignored."
            echo "All files needed are generated using the current working directory!"
            filename="${PWD}"

            filename="$(basename $(dirname "${filename}"))_$(basename ${filename}).go"
            test_file="${filename%.*}_test.go"

            touch "${filename,,}" "${test_file,,}"

            # write package line into the generated files
            echo "package main" > "${filename}"
            echo "package main" > "${test_file}"

            file_extension_check "${filename}" "go"
            file_extension_check "${test_file}" "go"

            generate_go_file "main.go"
            format_code "main.go"

            go mod init $(basename "${PWD}")
            go mod tidy

            go build .
            go run .
        ;;
        t)
            go test -v -cover .
        ;;
        h)
            help
            exit 1
        ;;
        *)
            echo "invalid option specified."
            exit 1
        ;;
    esac
done
