#!/usr/bin/env bash
# Description: Make a script that launches golang program
# Date: 21/04/25
# Author: omitida

function help() {
    echo "
    ./makego [options] <filename>

    options
    =======
    -b  build and run a go file. This generate an executable file.
    -d  delete a go file.
    -g  generate and run a generic go file.
    -h  print the help function of the script.
    -t  to run a test file in the current working directory
    -s  to create a standalone go file
    -n  to create all the files needed including the test file.
    -r  to run a specified go file
    -R  to run a directory
    "
}

# write out a basic go file
function generate_go_file() {
    filename="${1}"

    if [[ -e "${filename}" ]]; then
        echo "The file ${filename} exists, and can't be overwritten."
        exit 1
    fi

    # basic golang line to write to file
    echo "
        package main

        import (
            \"fmt\"
        )

        func main() {
            fmt.Println(\"Start Here...\")
        }
        " > "${filename}"
}

# check if the file has an extension check
# if it doesn't add one: Which should be go
function file_extension_check() {
    filename=${1}
    expected_extension="${2}"
    ext="${filename##*.}"
    if [[ "${ext}" != "${expected_extension}" ]]; then
        filename="${filename}.go"
    fi
}

function format_code() {
    filename=${1}
    gofmt "${filename}" > "${filename}_tmp"
    cat "${filename}_tmp" > "${filename}"
    rm "${filename}_tmp"
}

function make_a_test_file() {
    filename="${1}"
    filename="${filename%.*}"

    echo "
        package ${filename}

        import (
            \"testing\"
        )

        func TestGeneric(t *testing.T) {
            ans := 2 + 5
            if ans != 7 {
                t.Error(\"Maths doesn't work Again!...\")
            }
        }
            " > "${filename}_test.go"

}

# check and start the script here
if [[ "${#}" -ne 2 ]]; then
    help
    exit 1
fi

# options string to use
optstring="b:d:g:r:R:n:T:t:s:h"

while getopts "${optstring}" opt; do
    case "${opt}" in
        b)
            filename="${OPTARG}"

            # call the function with parameters
            file_extension_check "${filename,,}" "go"
            generate_go_file "${filename}"
            format_code "${filename}"

            go mod init $(basename "${PWD}")
            go mod tidy

            go build .
            go run .
        ;;
        d)
            filename="${OPTARG}"
            filename=$(ls | grep -i "${filename}")

            if ! [[ -e "${filename}" ]]; then
                echo "${OPTARG} doesn't exists."
                exit 0
            fi

            while read -p "Do you want to delete the ${filename}? [yn]: " -r ans; do
                case "${ans,,}" in
                    y)
                        rm -rf "${filename}"
                        echo "${filename} deleted."
                        exit 0
                        ;;
                    n)
                        echo "${filename} NOT deleted."
                        exit 0
                        ;;
                    *)
                    echo "Use either y or n."
                    continue
                    ;;
                esac
            done
        ;;
        g)
            filename="${OPTARG}"

            # call the function with parameters
            file_extension_check "${filename,,}" "go"
            generate_go_file "${filename}"
            format_code "${filename}"

            directory="${filename%.*}"
            mkdir "${directory}" && mv "${filename}" "${directory}/main.go"
            cd "${directory}"
            go mod init "${directory}"
            go build .
            go run .

            # rm the binary file NOT the directory
            rm "${directory}"
        ;;
        r)
             filename="${OPTARG}"
             file_extension_check "${filename,,}" "go"
             go run "${filename}"
        ;;
        R)
            directory="${OPTARG}"
            cd "${directory}"
            result=$(ls "${directory}" 2&>>/dev/null | grep -i 'go.mod' | wc -l)
            if [[ "${result}" == 0 ]]; then
                ./"{0}" -g "${directory}"
                go build .
                go run .
                exit 0
            fi
            go build .
            go run .
            while read -p "Retain the binary file [y|n]?: " ans; do
                case "${ans}" in
                    y)
                        echo "${directory} is preserved!"
                        exit 0
                        ;;
                    n)
                        rm "${directory}"  # clean up by deleting the binary file
                        exit 0
                        ;;
                    *)
                        echo "Invalid answer: ${ans}. Use either y or n."
                        continue
                        ;;
                esac
            done
            ;;
        n)
            filename="${OPTARG}"
            echo "Filename ${filename} is ignored."
            echo "All files needed are generated using the current working directory!"
            filename="${PWD}"

            filename="$(basename $(dirname "${filename}"))_$(basename ${filename}).go"
            test_file="${filename%.*}_test.go"

            touch "${filename,,}" "${test_file,,}"

            # write package line into the generated files
            echo "package main" > "${filename}"
            echo "package main" > "${test_file}"

            file_extension_check "${filename}" "go"
            file_extension_check "${test_file}" "go"

            generate_go_file "main.go"
            format_code "main.go"

            go mod init $(basename "${PWD}")
            go mod tidy

            go build .
            go run .
        ;;
        s)
            filename="${OPTARG}"

            # call the function with parameters
            file_extension_check "${filename,,}" "go"
            generate_go_file "${filename}"
            format_code "${filename}"

            go run "${filename}"
        ;;
        T)
            file="${OPTARG}"
            if [[ -f "${file}" ]]; then
                make_a_test_file "${file}"

                go fmt .
                go test -v -cover .
            else
                echo "need to be a file!"
                exit 1
            fi
            ;;
        t)
            go test -v -cover .
        ;;
        h)
            help
            exit 1
        ;;
        *)
            echo "invalid option specified."
            exit 1
        ;;
    esac
done
